version: "3.8"

services:
  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  # Serviço para a aplicação NestJS
  app:
    build: .
    restart: always
    environment:
      DB_DIALECT: ${DB_DIALECT}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    depends_on:
      - db
    ports:
      - "3333:3333"

volumes:
  db-data:
